/// Flutter icons Icons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons
///      fonts:
///       - asset: fonts/Icons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Icons {
  Icons._();

  static const _kFontFam = 'Icons';
  static const String? _kFontPkg = null;

  static const IconData blur_circular = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessibility = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData access_alarms = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assistant_photo = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_turned_in = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_high = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData av_timer = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airport_shuttle = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData router = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vpn_key = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallpaper = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vibration = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_user = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData system_update_alt = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_input_svideo = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_overscan = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_applications = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData satellite = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData present_to_all = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData panorama_wide_angle = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData panorama_fish_eye = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pan_tool = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pages = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_with = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData looks = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xf1b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_alt = IconData(0xf5de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_crash = IconData(0xf5e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_side = IconData(0xf5e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
